mergeSort [] = []
mergeSort [x] = [x]
mergeSort xs = merge front back
    where halfLength = (length xs) `div` 2
          front = mergeSort $ take halfLength xs
          back = mergeSort $ drop halfLength xs
          merge xs [] = xs
          merge [] ys = ys
          merge xs@(x:xs') ys@(y:ys') = if x<y then x : merge xs' ys else y : merge xs ys'